name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Ionic build android release
        run: ionic capacitor build android --release --prod

      - name: Generate Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle
        
      - name: Sign app bundle
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: ./android/app/build/outputs/bundle/debug/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0

      - name: Upload App bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedFile}}
