name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Ionic build android release
        run: ionic capacitor build android --release --prod

      - name: Generate Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: Upload bundle
        uses: actions/upload-artifact@v1
        with:
          name: high-card
          path: ./android/app/build/outputs/bundle/debug/app-debug.aab
